update github workflow

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -75,10 +75,12 @@ jobs:
           name: hugo-site
           path: ./public
 
+      - name: Check downloaded artifact
+        run: ls -lah ./public || echo "Artifact download failed!"
+
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
-
-      - name: Debug Build Output
-        run: ls -lah ./public
+        with:
+          artifact_name: github-pages
       
